INSERT INTO GENRE_DICTIONARY (GENRE_NAME)
VALUES ('Комедия');
INSERT INTO GENRE_DICTIONARY (GENRE_NAME)
VALUES ('Драма');
INSERT INTO GENRE_DICTIONARY (GENRE_NAME)
VALUES ('Мультфильм');
INSERT INTO GENRE_DICTIONARY (GENRE_NAME)
VALUES ('Триллер');
INSERT INTO GENRE_DICTIONARY (GENRE_NAME)
VALUES ('Документальный');
INSERT INTO GENRE_DICTIONARY (GENRE_NAME)
VALUES ('Боевик');

INSERT INTO MPA_DICTIONARY (RATING)
VALUES ('G');
INSERT INTO MPA_DICTIONARY (RATING)
VALUES ('PG');
INSERT INTO MPA_DICTIONARY (RATING)
VALUES ('PG-13');
INSERT INTO MPA_DICTIONARY (RATING)
VALUES ('R');
INSERT INTO MPA_DICTIONARY (RATING)
VALUES ('NC-17');

INSERT INTO EVENT_DICTIONARY (EVENT_NAME)
VALUES ('FRIEND'),('LIKE'),('REVIEW');

INSERT INTO OPERATION_DICTIONARY (OPERATION_NAME)
VALUES ('ADD'),('UPDATE'),('REMOVE');